name: genomedata
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - six
  - hdf5
  - zlib
  - pytables >= 3.4.3
  - path.py
  - textinput
  - bedtools
  - ucsc-bigwigtobedgraph